
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: required

addons:
  apt:
    packages:
      - autotools-dev
      - libcap-dev
      - libssl-dev
      - g++
      - libfuse-dev
      - pkg-config
      - libattr1-dev
      - patch
      - python-dev
      - unzip
      - uuid-dev
      - libc6-dev
      - valgrind
      - voms-dev
      - gdb
      - lldb

before_script:
  - ulimit -c unlimited -S
  - mkdir -p build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install gdb Caskroom/cask/osxfuse ; fi

script:
  - ci/run_cpplint.sh
  # make -j stresses the memory of travis
  - cd build && cmake -DBUILD_UNITTESTS=yes -DBUILD_PRELOADER=yes .. && make
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$PWD/externals/build_tbb/build_release ; fi
  - test/unittests/cvmfs_unittests --gtest_shuffle --gtest_filter="-*Slow:T_Dns.CaresResolverLocalhost:T_Dns.NormalResolverCombined:T_Dns.CaresResolverMany"


after_failure:
  - echo "t a a bt" | gdb -ex run --args test/unittests/cvmfs_unittests --gtest_shuffle --gtest_filter="-*Slow:T_Dns.CaresResolverLocalhost:T_Dns.NormalResolverCombined:T_Dns.CaresResolverMany"
