
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: required

addons:
  apt:
    packages:
      - autotools-dev
      - libcap-dev
      - libssl-dev
      - g++
      - libfuse-dev
      - pkg-config
      - libattr1-dev
      - patch
      - python-dev
      - unzip
      - uuid-dev
      - libc6-dev
      - valgrind
      - voms-dev
      - gdb

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install Caskroom/cask/osxfuse ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --yes rng-tools || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo rm -f /dev/random; sudo mknod -m 0666 /dev/random c 1 9; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo HRNGDEVICE=/dev/urandom | sudo tee /etc/default/rng-tools; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo /etc/init.d/rng-tools restart; fi

script:
  - ci/run_travis.sh

notifications:
  email: false
