
language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

sudo: required

addons:
  apt:
    packages:
      - autotools-dev
      - libcap-dev
      - libssl-dev
      - g++
      - libfuse-dev
      - pkg-config
      - libattr1-dev
      - patch
      - python-dev
      - unzip
      - uuid-dev
      - libc6-dev
      - valgrind
      - voms-dev
      - gdb
      - lldb

before_script:
  - mkdir -p build
  - python --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi

script:
  - cd build && cmake -DBUILD_UNITTESTS=yes -DBUILD_PRELOADER=yes .. && make && test/unittests/cvmfs_unittests --gtest_shuffle --gtest_filter="-*Slow:T_Dns.CaresResolverLocalhost:T_Dns.NormalResolverCombined"
  - ../ci/run_cpplint.sh

