name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      CCACHE_MAXSIZE: 400M
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            autotools-dev \
            build-essential \
            cmake \
            cpio \
            debhelper \
            devscripts \
            gdb \
            gcc \
            git \
            libattr1-dev \
            libcap-dev \
            libffi-dev \
            libfuse-dev \
            libssl-dev \
            pkg-config \
            python-dev \
            python-setuptools \
            ruby \
            ruby-dev \
            rubygems \
            unzip \
            uuid-dev \
            valgrind \
            autoconf \
            bison \
            doxygen \
            graphviz \
            gsfonts \
            dh-systemd \
            flex \
            libhesiod-dev \
            libkrb5-dev \
            libldap2-dev \
            libsasl2-dev \
            libxml2-dev \
            sssd-common \
            ccache
      - name: "Set up github cache for ccache"
        uses: actions/cache@v1.1.2
        with:
          path: "~/.ccache"
          key: ${{ runner.os }}-ccache-1
      - name: "Setup ccache path"
        run: echo "::add-path::/usr/lib/ccache/"
      - name: "Create build directory"
        run: mkdir build
      - name: "Run CMAKE"
        working-directory: build
        run: cmake BUILD_ALL=ON ..
      - name: "Compile it"
        working-directory: build
        run: make
      - name: "Print out ccache stats"
        run: ccache -s
