name: Test
on: [push, pull_request]
runs-on: ubuntu-18.04

jobs:
  build:
    name: Build
    container:
      image: golang:1.13
    steps:
      - uses: actions/checkout@v2
      - name: run make
        run: make 
